### ISSUE TITLE
Möglicher Fehler in Template.Parser

### ISSUE THREAD

**Issue by ladymagnetic** [ladymagnetic/semanticcms#19]
Beim Aufruf von GetButton() bekomme ich folgende Meldung:

Fatal error: Cannot use object of type DOMElement as array in C:\xampp\htdocs\cms\lib\TemplateParser.class.php on line 296

**Comment by Resi12** [comment]
Tritt das bei dir nur bei GetButton auf oder auch bei den anderen?

**Comment by Resi12** [comment]
Fehler sollte etz behoben sein.
