### ISSUE TITLE
Fehler in Templateconstruction

### ISSUE THREAD

**Issue by Mirjam1** [ladymagnetic/semanticcms#21]
Falls noch nicht bekannt, siehe unten:

Notice: Undefined index: SearchField in D:\xampp\htdocs\Code\TemplateConstruction.php on line 189

Notice: Undefined index: Login in D:\xampp\htdocs\Code\TemplateConstruction.php on line 190

**Comment by Resi12** [comment]
Doch is schon bekannt steht auch in der doku drin

**Comment by MilleniaNox** [comment]
Ok aber der Fehler sollte am Ende nicht mehr auf der Seite stehen...Also falls es gar nicht mehr funktionieren sollte, am besten auskommentieren/löschen oder so :)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.01.17, 18:00, Resi12 <notifications@github.com> schrieb:

  
    
      Doch is schon bekannt steht auch in der doku drin
